spring:
  profiles:
    active: local

---
## LOCAL PROP
server:
  port: 8080

spring:
  profiles: local

  jackson:
    default-property-inclusion: non_null

  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./test_db;AUTO_SERVER=TRUE
    username: franc
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace


